In [1]:
import pandas as pd
import numpy as np

In [ ]:


mg = {
    'Name': ["Peter", "Quagmire", "Luois", "Stewie", "Brian", "Griffins", "Giant Dog", "Meg", "Obama", "Chris", "Leg", "Putin"],
    'NET': [51, 63, 59, 45, 85, 74, 95, 96, 23, 65, 22.2, 14],
    'Dev': [45, 52, 23, 14, 25, 63, 9, 74, 50, 63.2, 66, 12],
    'WeD': [36, 25, 5, 62, 19, 18, 55, 65, 44, 70, 69, 33.6],
    'PWD': [52, 66, 23, 12, 21, 41, 52, 25, 36, 45.6, 77, 63],
    'JSC': [25, 14, 52, 63, 45, 21, 85, 96, 45, 63, 55.3, 23],
    'DVS': [75, 85, 96, 5, 45, 63, 47, 65, 23.6, 52, 60, 50],
    'EVS': [30, 66, 56, 45, 32.3, 44, 51, 25, 36, 47, 58, 56]
}

gh = pd.DataFrame(mg)
gh

         Name   NET   Dev   WeD   PWD   JSC   DVS   EVS
0       Peter  51.0  45.0  36.0  52.0  25.0  75.0  30.0
1    Quagmire  63.0  52.0  25.0  66.0  14.0  85.0  66.0
2       Luois  59.0  23.0   5.0  23.0  52.0  96.0  56.0
3      Stewie  45.0  14.0  62.0  12.0  63.0   5.0  45.0
4       Brian  85.0  25.0  19.0  21.0  45.0  45.0  32.3
5    Griffins  74.0  63.0  18.0  41.0  21.0  63.0  44.0
6   Giant Dog  95.0   9.0  55.0  52.0  85.0  47.0  51.0
7         Meg  96.0  74.0  65.0  25.0  96.0  65.0  25.0
8       Obama  23.0  50.0  44.0  36.0  45.0  23.6  36.0
9       Chris  65.0  63.2  70.0  45.6  63.0  52.0  47.0
10        Leg  22.2  66.0  69.0  77.0  55.3  60.0  58.0
11      Putin  14.0  12.0  33.6  63.0  23.0  50.0  56.0

## **Basic Info & Access**

In [23]:
gh.head()

       Name   NET   Dev   WeD   PWD   JSC   DVS   EVS
0     Peter  51.0  45.0  36.0  52.0  25.0  75.0  30.0
1  Quagmire  63.0  52.0  25.0  66.0  14.0  85.0  66.0
2     Luois  59.0  23.0   5.0  23.0  52.0  96.0  56.0
3    Stewie  45.0  14.0  62.0  12.0  63.0   5.0  45.0
4     Brian  85.0  25.0  19.0  21.0  45.0  45.0  32.3

In [24]:
gh.tail()

     Name   NET   Dev   WeD   PWD   JSC   DVS   EVS
7     Meg  96.0  74.0  65.0  25.0  96.0  65.0  25.0
8   Obama  23.0  50.0  44.0  36.0  45.0  23.6  36.0
9   Chris  65.0  63.2  70.0  45.6  63.0  52.0  47.0
10    Leg  22.2  66.0  69.0  77.0  55.3  60.0  58.0
11  Putin  14.0  12.0  33.6  63.0  23.0  50.0  56.0

In [25]:
gh.shape

(12, 8)

In [26]:
gh.columns

Index(['Name', 'NET', 'Dev', 'WeD', 'PWD', 'JSC', 'DVS', 'EVS'], dtype='object')

In [27]:
gh.dtypes

Name     object
NET     float64
Dev     float64
WeD     float64
PWD     float64
JSC     float64
DVS     float64
EVS     float64
dtype: object

In [28]:
gh.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    12 non-null     object
 1   NET     12 non-null     float64
 2   Dev     12 non-null     float64
 3   WeD     12 non-null     float64
 4   PWD     12 non-null     float64
 5   JSC     12 non-null     float64
 6   DVS     12 non-null     float64
 7   EVS     12 non-null     float64
dtypes: float64(7), object(1)
memory usage: 900.0+ bytes

In [29]:
gh.describe()

,NET,Dev,WeD,PWD,JSC,DVS,EVS
count,12.000000,12.000000,12.000000,12.000000,12.000000,12.000000,12.000000
mean,57.683333,41.350000,41.800000,42.800000,48.941667,55.550000,45.525000
std,27.850962,23.512801,22.328294,20.170365,25.652661,24.955105,12.638263
min,14.000000,9.000000,5.000000,12.000000,14.000000,5.000000,25.000000
25%,39.500000,20.750000,23.500000,24.500000,24.500000,46.500000,35.075000
50%,61.000000,47.500000,40.000000,43.300000,48.500000,56.000000,46.000000
75%,76.750000,63.050000,62.750000,54.750000,63.000000,67.500000,56.000000
max,96.000000,74.000000,70.000000,77.000000,96.000000,96.000000,66.000000

In [30]:
gh['Name']

0         Peter
1      Quagmire
2         Luois
3        Stewie
4         Brian
5      Griffins
6     Giant Dog
7           Meg
8         Obama
9         Chris
10          Leg
11        Putin
Name: Name, dtype: object

In [31]:
gh[['Name', 'NET']]

         Name   NET
0       Peter  51.0
1    Quagmire  63.0
2       Luois  59.0
3      Stewie  45.0
4       Brian  85.0
5    Griffins  74.0
6   Giant Dog  95.0
7         Meg  96.0
8       Obama  23.0
9       Chris  65.0
10        Leg  22.2
11      Putin  14.0

In [32]:
gh.iloc[0]

Name    Peter
NET      51.0
Dev      45.0
WeD      36.0
PWD      52.0
JSC      25.0
DVS      75.0
EVS      30.0
Name: 0, dtype: object

## **Filtering & Conditions**

In [33]:
gh[gh['NET'] > 70]

        Name   NET   Dev   WeD   PWD   JSC   DVS   EVS
4      Brian  85.0  25.0  19.0  21.0  45.0  45.0  32.3
5   Griffins  74.0  63.0  18.0  41.0  21.0  63.0  44.0
6  Giant Dog  95.0   9.0  55.0  52.0  85.0  47.0  51.0
7        Meg  96.0  74.0  65.0  25.0  96.0  65.0  25.0

In [34]:
gh[(gh['NET'] > 70) & (gh['Dev'] < 60)]

        Name   NET   Dev   WeD   PWD   JSC   DVS   EVS
4      Brian  85.0  25.0  19.0  21.0  45.0  45.0  32.3
6  Giant Dog  95.0   9.0  55.0  52.0  85.0  47.0  51.0

In [35]:
gh[gh['Name'].str.startswith('G')]

        Name   NET   Dev   WeD   PWD   JSC   DVS   EVS
5   Griffins  74.0  63.0  18.0  41.0  21.0  63.0  44.0
6  Giant Dog  95.0   9.0  55.0  52.0  85.0  47.0  51.0

In [36]:
gh[gh['JSC'] == gh['JSC'].max()]

  Name   NET   Dev   WeD   PWD   JSC   DVS   EVS
7  Meg  96.0  74.0  65.0  25.0  96.0  65.0  25.0

In [37]:
gh.query("PWD > 50")

         Name   NET   Dev   WeD   PWD   JSC   DVS   EVS
0       Peter  51.0  45.0  36.0  52.0  25.0  75.0  30.0
1    Quagmire  63.0  52.0  25.0  66.0  14.0  85.0  66.0
6   Giant Dog  95.0   9.0  55.0  52.0  85.0  47.0  51.0
10        Leg  22.2  66.0  69.0  77.0  55.3  60.0  58.0
11      Putin  14.0  12.0  33.6  63.0  23.0  50.0  56.0

In [38]:
gh[gh['Name'].isin(['Obama', 'Putin'])]

     Name   NET   Dev   WeD   PWD   JSC   DVS   EVS
8   Obama  23.0  50.0  44.0  36.0  45.0  23.6  36.0
11  Putin  14.0  12.0  33.6  63.0  23.0  50.0  56.0

In [39]:
gh[~gh['Name'].isin(['Obama'])]

         Name   NET   Dev   WeD   PWD   JSC   DVS   EVS
0       Peter  51.0  45.0  36.0  52.0  25.0  75.0  30.0
1    Quagmire  63.0  52.0  25.0  66.0  14.0  85.0  66.0
2       Luois  59.0  23.0   5.0  23.0  52.0  96.0  56.0
3      Stewie  45.0  14.0  62.0  12.0  63.0   5.0  45.0
4       Brian  85.0  25.0  19.0  21.0  45.0  45.0  32.3
5    Griffins  74.0  63.0  18.0  41.0  21.0  63.0  44.0
6   Giant Dog  95.0   9.0  55.0  52.0  85.0  47.0  51.0
7         Meg  96.0  74.0  65.0  25.0  96.0  65.0  25.0
9       Chris  65.0  63.2  70.0  45.6  63.0  52.0  47.0
10        Leg  22.2  66.0  69.0  77.0  55.3  60.0  58.0
11      Putin  14.0  12.0  33.6  63.0  23.0  50.0  56.0

In [40]:
gh[gh['DVS'].between(50, 70)]

        Name   NET   Dev   WeD   PWD   JSC   DVS   EVS
5   Griffins  74.0  63.0  18.0  41.0  21.0  63.0  44.0
7        Meg  96.0  74.0  65.0  25.0  96.0  65.0  25.0
9      Chris  65.0  63.2  70.0  45.6  63.0  52.0  47.0
10       Leg  22.2  66.0  69.0  77.0  55.3  60.0  58.0
11     Putin  14.0  12.0  33.6  63.0  23.0  50.0  56.0

In [41]:
gh.nlargest(5, 'Dev')

        Name   NET   Dev   WeD   PWD   JSC   DVS   EVS
7        Meg  96.0  74.0  65.0  25.0  96.0  65.0  25.0
10       Leg  22.2  66.0  69.0  77.0  55.3  60.0  58.0
9      Chris  65.0  63.2  70.0  45.6  63.0  52.0  47.0
5   Griffins  74.0  63.0  18.0  41.0  21.0  63.0  44.0
1   Quagmire  63.0  52.0  25.0  66.0  14.0  85.0  66.0

In [42]:
gh.nsmallest(3, 'PWD')

     Name   NET   Dev   WeD   PWD   JSC   DVS   EVS
3  Stewie  45.0  14.0  62.0  12.0  63.0   5.0  45.0
4   Brian  85.0  25.0  19.0  21.0  45.0  45.0  32.3
2   Luois  59.0  23.0   5.0  23.0  52.0  96.0  56.0

## **Column Operations**

In [44]:
gh['Total'] = gh[['NET','Dev','WeD','PWD','JSC','DVS','EVS']].sum(axis=1) 
gh['Total']

0     314.0
1     371.0
2     314.0
3     246.0
4     272.3
5     324.0
6     394.0
7     446.0
8     257.6
9     405.8
10    407.5
11    251.6
Name: Total, dtype: float64

In [45]:
gh['Average'] = gh['Total'] / 7  
gh['Average']

0     44.857143
1     53.000000
2     44.857143
3     35.142857
4     38.900000
5     46.285714
6     56.285714
7     63.714286
8     36.800000
9     57.971429
10    58.214286
11    35.942857
Name: Average, dtype: float64

In [46]:
gh['Result'] = gh['Average'].apply(lambda x: 'Pass' if x >= 40 else 'Fail')
gh['Result']

0     Pass
1     Pass
2     Pass
3     Fail
4     Fail
5     Pass
6     Pass
7     Pass
8     Fail
9     Pass
10    Pass
11    Fail
Name: Result, dtype: object

In [47]:
gh['Grade'] = pd.cut(gh['Average'], bins=[0,40,60,80,100], labels=['F','C','B','A'])
gh['Grade']

0     C
1     C
2     C
3     F
4     F
5     C
6     C
7     B
8     F
9     C
10    C
11    F
Name: Grade, dtype: category
Categories (4, object): ['F' < 'C' < 'B' < 'A']

In [50]:
gh

,Name,NET,Dev,WeD,PWD,JSC,DVS,EVS,Average,Result,Grade
0,Peter,51.0,45.0,36.0,52.0,25.0,75.0,30.0,44.857143,Pass,C
1,Quagmire,63.0,52.0,25.0,66.0,14.0,85.0,66.0,53.000000,Pass,C
2,Luois,59.0,23.0,5.0,23.0,52.0,96.0,56.0,44.857143,Pass,C
3,Stewie,45.0,14.0,62.0,12.0,63.0,5.0,45.0,35.142857,Fail,F
4,Brian,85.0,25.0,19.0,21.0,45.0,45.0,32.3,38.900000,Fail,F
5,Griffins,74.0,63.0,18.0,41.0,21.0,63.0,44.0,46.285714,Pass,C
6,Giant Dog,95.0,9.0,55.0,52.0,85.0,47.0,51.0,56.285714,Pass,C
7,Meg,96.0,74.0,65.0,25.0,96.0,65.0,25.0,63.714286,Pass,B
8,Obama,23.0,50.0,44.0,36.0,45.0,23.6,36.0,36.800000,Fail,F
9,Chris,65.0,63.2,70.0,45.6,63.0,52.0,47.0,57.971429,Pass,C
10,Leg,22.2,66.0,69.0,77.0,55.3,60.0,58.0,58.214286,Pass,C
11,Putin,14.0,12.0,33.6,63.0,23.0,50.0,56.0,35.942857,Fail,F

In [51]:
gh.rename(columns={'NET': 'Network'}, inplace=True)

In [53]:
gh

,Name,Network,Dev,WeD,PWD,JSC,DVS,EVS,Average,Result,Grade
0,Peter,51.0,45.0,36.0,52.0,25.0,75.0,30.0,44.857143,Pass,C
1,Quagmire,63.0,52.0,25.0,66.0,14.0,85.0,66.0,53.000000,Pass,C
2,Luois,59.0,23.0,5.0,23.0,52.0,96.0,56.0,44.857143,Pass,C
3,Stewie,45.0,14.0,62.0,12.0,63.0,5.0,45.0,35.142857,Fail,F
4,Brian,85.0,25.0,19.0,21.0,45.0,45.0,32.3,38.900000,Fail,F
5,Griffins,74.0,63.0,18.0,41.0,21.0,63.0,44.0,46.285714,Pass,C
6,Giant Dog,95.0,9.0,55.0,52.0,85.0,47.0,51.0,56.285714,Pass,C
7,Meg,96.0,74.0,65.0,25.0,96.0,65.0,25.0,63.714286,Pass,B
8,Obama,23.0,50.0,44.0,36.0,45.0,23.6,36.0,36.800000,Fail,F
9,Chris,65.0,63.2,70.0,45.6,63.0,52.0,47.0,57.971429,Pass,C
10,Leg,22.2,66.0,69.0,77.0,55.3,60.0,58.0,58.214286,Pass,C
11,Putin,14.0,12.0,33.6,63.0,23.0,50.0,56.0,35.942857,Fail,F

In [54]:
gh['Name'] = gh['Name'].str.upper()

In [55]:
gh

,Name,Network,Dev,WeD,PWD,JSC,DVS,EVS,Average,Result,Grade
0,PETER,51.0,45.0,36.0,52.0,25.0,75.0,30.0,44.857143,Pass,C
1,QUAGMIRE,63.0,52.0,25.0,66.0,14.0,85.0,66.0,53.000000,Pass,C
2,LUOIS,59.0,23.0,5.0,23.0,52.0,96.0,56.0,44.857143,Pass,C
3,STEWIE,45.0,14.0,62.0,12.0,63.0,5.0,45.0,35.142857,Fail,F
4,BRIAN,85.0,25.0,19.0,21.0,45.0,45.0,32.3,38.900000,Fail,F
5,GRIFFINS,74.0,63.0,18.0,41.0,21.0,63.0,44.0,46.285714,Pass,C
6,GIANT DOG,95.0,9.0,55.0,52.0,85.0,47.0,51.0,56.285714,Pass,C
7,MEG,96.0,74.0,65.0,25.0,96.0,65.0,25.0,63.714286,Pass,B
8,OBAMA,23.0,50.0,44.0,36.0,45.0,23.6,36.0,36.800000,Fail,F
9,CHRIS,65.0,63.2,70.0,45.6,63.0,52.0,47.0,57.971429,Pass,C
10,LEG,22.2,66.0,69.0,77.0,55.3,60.0,58.0,58.214286,Pass,C
11,PUTIN,14.0,12.0,33.6,63.0,23.0,50.0,56.0,35.942857,Fail,F

In [56]:
gh['Name Length'] = gh['Name'].str.len()

In [58]:
gh[['Name Length']]

    Name Length
0             5
1             8
2             5
3             6
4             5
5             8
6             9
7             3
8             5
9             5
10            3
11            5

In [59]:
gh['Rounded Dev'] = gh['Dev'].round(0)

In [60]:
gh['Rounded Dev']

0     45.0
1     52.0
2     23.0
3     14.0
4     25.0
5     63.0
6      9.0
7     74.0
8     50.0
9     63.0
10    66.0
11    12.0
Name: Rounded Dev, dtype: float64

In [61]:
gh['DVS x 2'] = gh['DVS'] * 2

In [62]:
gh['DVS x 2']

0     150.0
1     170.0
2     192.0
3      10.0
4      90.0
5     126.0
6      94.0
7     130.0
8      47.2
9     104.0
10    120.0
11    100.0
Name: DVS x 2, dtype: float64

## **Aggregation & Grouping**

In [63]:
gh.groupby('Result')['Average'].mean()

Result
Fail    36.696429
Pass    53.148214
Name: Average, dtype: float64

In [64]:
gh.groupby('Grade')['EVS'].mean()

C:\Users\sarit\AppData\Local\Temp\ipykernel_3800\1088405017.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  gh.groupby('Grade')['EVS'].mean()

Grade
F    42.325000
C    50.285714
B    25.000000
A          NaN
Name: EVS, dtype: float64

In [65]:
gh.groupby('Result').size()

Result
Fail    4
Pass    8
dtype: int64

In [66]:
gh.groupby('Grade')[['Network','Dev']].sum()

C:\Users\sarit\AppData\Local\Temp\ipykernel_3800\3877917314.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  gh.groupby('Grade')[['Network','Dev']].sum()

       Network    Dev
Grade
F        167.0  101.0
C        429.2  321.2
B         96.0   74.0
A          0.0    0.0

In [67]:
gh.pivot_table(index='Grade', values='PWD', aggfunc='max')

C:\Users\sarit\AppData\Local\Temp\ipykernel_3800\3099314990.py:1: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  gh.pivot_table(index='Grade', values='PWD', aggfunc='max')

        PWD
Grade
F      63.0
C      77.0
B      25.0

In [68]:
pd.crosstab(gh['Result'], gh['Grade'])

Grade   F  C  B
Result
Fail    4  0  0
Pass    0  7  1

In [69]:
gh['Rank'] = gh['Average'].rank(ascending=False)

In [70]:
gh['Rank']

0      7.5
1      5.0
2      7.5
3     12.0
4      9.0
5      6.0
6      4.0
7      1.0
8     10.0
9      3.0
10     2.0
11    11.0
Name: Rank, dtype: float64

In [71]:
gh.sort_values('Average', ascending=False, inplace=True)

In [72]:
gh

,Name,Network,Dev,WeD,PWD,JSC,DVS,EVS,Average,Result,Grade,Name Length,Rounded Dev,DVS x 2,Rank
7,MEG,96.0,74.0,65.0,25.0,96.0,65.0,25.0,63.714286,Pass,B,3,74.0,130.0,1.0
10,LEG,22.2,66.0,69.0,77.0,55.3,60.0,58.0,58.214286,Pass,C,3,66.0,120.0,2.0
9,CHRIS,65.0,63.2,70.0,45.6,63.0,52.0,47.0,57.971429,Pass,C,5,63.0,104.0,3.0
6,GIANT DOG,95.0,9.0,55.0,52.0,85.0,47.0,51.0,56.285714,Pass,C,9,9.0,94.0,4.0
1,QUAGMIRE,63.0,52.0,25.0,66.0,14.0,85.0,66.0,53.000000,Pass,C,8,52.0,170.0,5.0
5,GRIFFINS,74.0,63.0,18.0,41.0,21.0,63.0,44.0,46.285714,Pass,C,8,63.0,126.0,6.0
0,PETER,51.0,45.0,36.0,52.0,25.0,75.0,30.0,44.857143,Pass,C,5,45.0,150.0,7.5
2,LUOIS,59.0,23.0,5.0,23.0,52.0,96.0,56.0,44.857143,Pass,C,5,23.0,192.0,7.5
4,BRIAN,85.0,25.0,19.0,21.0,45.0,45.0,32.3,38.900000,Fail,F,5,25.0,90.0,9.0
8,OBAMA,23.0,50.0,44.0,36.0,45.0,23.6,36.0,36.800000,Fail,F,5,50.0,47.2,10.0
11,PUTIN,14.0,12.0,33.6,63.0,23.0,50.0,56.0,35.942857,Fail,F,5,12.0,100.0,11.0
3,STEWIE,45.0,14.0,62.0,12.0,63.0,5.0,45.0,35.142857,Fail,F,6,14.0,10.0,12.0

In [73]:
gh['Cumsum Dev'] = gh['Dev'].cumsum()

In [74]:
gh['Cumsum Dev']

7      74.0
10    140.0
9     203.2
6     212.2
1     264.2
5     327.2
0     372.2
2     395.2
4     420.2
8     470.2
11    482.2
3     496.2
Name: Cumsum Dev, dtype: float64

In [75]:
gh['Zscore'] = (gh['Average'] - gh['Average'].mean()) / gh['Average'].std()

In [76]:
gh['Zscore']

7     1.616336
10    1.062451
9     1.037994
6     0.868232
1     0.537340
5    -0.138831
0    -0.282697
2    -0.282697
4    -0.882619
8    -1.094102
11   -1.180421
3    -1.260986
Name: Zscore, dtype: float64

## **Cleanup, Sampling, Export**

In [77]:
gh.isnull().sum()

Name           0
Network        0
Dev            0
WeD            0
PWD            0
JSC            0
DVS            0
EVS            0
Average        0
Result         0
Grade          0
Name Length    0
Rounded Dev    0
DVS x 2        0
Rank           0
Cumsum Dev     0
Zscore         0
dtype: int64

In [79]:
gh.duplicated().sum()

0

In [80]:
gh.reset_index(drop=True, inplace=True)

In [81]:
gh

,Name,Network,Dev,WeD,PWD,JSC,DVS,EVS,Average,Result,Grade,Name Length,Rounded Dev,DVS x 2,Rank,Cumsum Dev,Zscore
0,MEG,96.0,74.0,65.0,25.0,96.0,65.0,25.0,63.714286,Pass,B,3,74.0,130.0,1.0,74.0,1.616336
1,LEG,22.2,66.0,69.0,77.0,55.3,60.0,58.0,58.214286,Pass,C,3,66.0,120.0,2.0,140.0,1.062451
2,CHRIS,65.0,63.2,70.0,45.6,63.0,52.0,47.0,57.971429,Pass,C,5,63.0,104.0,3.0,203.2,1.037994
3,GIANT DOG,95.0,9.0,55.0,52.0,85.0,47.0,51.0,56.285714,Pass,C,9,9.0,94.0,4.0,212.2,0.868232
4,QUAGMIRE,63.0,52.0,25.0,66.0,14.0,85.0,66.0,53.000000,Pass,C,8,52.0,170.0,5.0,264.2,0.537340
5,GRIFFINS,74.0,63.0,18.0,41.0,21.0,63.0,44.0,46.285714,Pass,C,8,63.0,126.0,6.0,327.2,-0.138831
6,PETER,51.0,45.0,36.0,52.0,25.0,75.0,30.0,44.857143,Pass,C,5,45.0,150.0,7.5,372.2,-0.282697
7,LUOIS,59.0,23.0,5.0,23.0,52.0,96.0,56.0,44.857143,Pass,C,5,23.0,192.0,7.5,395.2,-0.282697
8,BRIAN,85.0,25.0,19.0,21.0,45.0,45.0,32.3,38.900000,Fail,F,5,25.0,90.0,9.0,420.2,-0.882619
9,OBAMA,23.0,50.0,44.0,36.0,45.0,23.6,36.0,36.800000,Fail,F,5,50.0,47.2,10.0,470.2,-1.094102
10,PUTIN,14.0,12.0,33.6,63.0,23.0,50.0,56.0,35.942857,Fail,F,5,12.0,100.0,11.0,482.2,-1.180421
11,STEWIE,45.0,14.0,62.0,12.0,63.0,5.0,45.0,35.142857,Fail,F,6,14.0,10.0,12.0,496.2,-1.260986

In [82]:
gh.set_index('Name', inplace=True)

In [83]:
gh

,Network,Dev,WeD,PWD,JSC,DVS,EVS,Average,Result,Grade,Name Length,Rounded Dev,DVS x 2,Rank,Cumsum Dev,Zscore
Name,,,,,,,,,,,,,,,,
MEG,96.0,74.0,65.0,25.0,96.0,65.0,25.0,63.714286,Pass,B,3,74.0,130.0,1.0,74.0,1.616336
LEG,22.2,66.0,69.0,77.0,55.3,60.0,58.0,58.214286,Pass,C,3,66.0,120.0,2.0,140.0,1.062451
CHRIS,65.0,63.2,70.0,45.6,63.0,52.0,47.0,57.971429,Pass,C,5,63.0,104.0,3.0,203.2,1.037994
GIANT DOG,95.0,9.0,55.0,52.0,85.0,47.0,51.0,56.285714,Pass,C,9,9.0,94.0,4.0,212.2,0.868232
QUAGMIRE,63.0,52.0,25.0,66.0,14.0,85.0,66.0,53.000000,Pass,C,8,52.0,170.0,5.0,264.2,0.537340
GRIFFINS,74.0,63.0,18.0,41.0,21.0,63.0,44.0,46.285714,Pass,C,8,63.0,126.0,6.0,327.2,-0.138831
PETER,51.0,45.0,36.0,52.0,25.0,75.0,30.0,44.857143,Pass,C,5,45.0,150.0,7.5,372.2,-0.282697
LUOIS,59.0,23.0,5.0,23.0,52.0,96.0,56.0,44.857143,Pass,C,5,23.0,192.0,7.5,395.2,-0.282697
BRIAN,85.0,25.0,19.0,21.0,45.0,45.0,32.3,38.900000,Fail,F,5,25.0,90.0,9.0,420.2,-0.882619
OBAMA,23.0,50.0,44.0,36.0,45.0,23.6,36.0,36.800000,Fail,F,5,50.0,47.2,10.0,470.2,-1.094102
PUTIN,14.0,12.0,33.6,63.0,23.0,50.0,56.0,35.942857,Fail,F,5,12.0,100.0,11.0,482.2,-1.180421
STEWIE,45.0,14.0,62.0,12.0,63.0,5.0,45.0,35.142857,Fail,F,6,14.0,10.0,12.0,496.2,-1.260986

In [84]:
gh.reset_index(inplace=True)

In [85]:
gh

,Name,Network,Dev,WeD,PWD,JSC,DVS,EVS,Average,Result,Grade,Name Length,Rounded Dev,DVS x 2,Rank,Cumsum Dev,Zscore
0,MEG,96.0,74.0,65.0,25.0,96.0,65.0,25.0,63.714286,Pass,B,3,74.0,130.0,1.0,74.0,1.616336
1,LEG,22.2,66.0,69.0,77.0,55.3,60.0,58.0,58.214286,Pass,C,3,66.0,120.0,2.0,140.0,1.062451
2,CHRIS,65.0,63.2,70.0,45.6,63.0,52.0,47.0,57.971429,Pass,C,5,63.0,104.0,3.0,203.2,1.037994
3,GIANT DOG,95.0,9.0,55.0,52.0,85.0,47.0,51.0,56.285714,Pass,C,9,9.0,94.0,4.0,212.2,0.868232
4,QUAGMIRE,63.0,52.0,25.0,66.0,14.0,85.0,66.0,53.000000,Pass,C,8,52.0,170.0,5.0,264.2,0.537340
5,GRIFFINS,74.0,63.0,18.0,41.0,21.0,63.0,44.0,46.285714,Pass,C,8,63.0,126.0,6.0,327.2,-0.138831
6,PETER,51.0,45.0,36.0,52.0,25.0,75.0,30.0,44.857143,Pass,C,5,45.0,150.0,7.5,372.2,-0.282697
7,LUOIS,59.0,23.0,5.0,23.0,52.0,96.0,56.0,44.857143,Pass,C,5,23.0,192.0,7.5,395.2,-0.282697
8,BRIAN,85.0,25.0,19.0,21.0,45.0,45.0,32.3,38.900000,Fail,F,5,25.0,90.0,9.0,420.2,-0.882619
9,OBAMA,23.0,50.0,44.0,36.0,45.0,23.6,36.0,36.800000,Fail,F,5,50.0,47.2,10.0,470.2,-1.094102
10,PUTIN,14.0,12.0,33.6,63.0,23.0,50.0,56.0,35.942857,Fail,F,5,12.0,100.0,11.0,482.2,-1.180421
11,STEWIE,45.0,14.0,62.0,12.0,63.0,5.0,45.0,35.142857,Fail,F,6,14.0,10.0,12.0,496.2,-1.260986

In [86]:
gh.sample(5)

,Name,Network,Dev,WeD,PWD,JSC,DVS,EVS,Average,Result,Grade,Name Length,Rounded Dev,DVS x 2,Rank,Cumsum Dev,Zscore
5,GRIFFINS,74.0,63.0,18.0,41.0,21.0,63.0,44.0,46.285714,Pass,C,8,63.0,126.0,6.0,327.2,-0.138831
9,OBAMA,23.0,50.0,44.0,36.0,45.0,23.6,36.0,36.800000,Fail,F,5,50.0,47.2,10.0,470.2,-1.094102
7,LUOIS,59.0,23.0,5.0,23.0,52.0,96.0,56.0,44.857143,Pass,C,5,23.0,192.0,7.5,395.2,-0.282697
1,LEG,22.2,66.0,69.0,77.0,55.3,60.0,58.0,58.214286,Pass,C,3,66.0,120.0,2.0,140.0,1.062451
0,MEG,96.0,74.0,65.0,25.0,96.0,65.0,25.0,63.714286,Pass,B,3,74.0,130.0,1.0,74.0,1.616336

In [87]:
gh.sort_index(inplace=True)

In [88]:
gh

,Name,Network,Dev,WeD,PWD,JSC,DVS,EVS,Average,Result,Grade,Name Length,Rounded Dev,DVS x 2,Rank,Cumsum Dev,Zscore
0,MEG,96.0,74.0,65.0,25.0,96.0,65.0,25.0,63.714286,Pass,B,3,74.0,130.0,1.0,74.0,1.616336
1,LEG,22.2,66.0,69.0,77.0,55.3,60.0,58.0,58.214286,Pass,C,3,66.0,120.0,2.0,140.0,1.062451
2,CHRIS,65.0,63.2,70.0,45.6,63.0,52.0,47.0,57.971429,Pass,C,5,63.0,104.0,3.0,203.2,1.037994
3,GIANT DOG,95.0,9.0,55.0,52.0,85.0,47.0,51.0,56.285714,Pass,C,9,9.0,94.0,4.0,212.2,0.868232
4,QUAGMIRE,63.0,52.0,25.0,66.0,14.0,85.0,66.0,53.000000,Pass,C,8,52.0,170.0,5.0,264.2,0.537340
5,GRIFFINS,74.0,63.0,18.0,41.0,21.0,63.0,44.0,46.285714,Pass,C,8,63.0,126.0,6.0,327.2,-0.138831
6,PETER,51.0,45.0,36.0,52.0,25.0,75.0,30.0,44.857143,Pass,C,5,45.0,150.0,7.5,372.2,-0.282697
7,LUOIS,59.0,23.0,5.0,23.0,52.0,96.0,56.0,44.857143,Pass,C,5,23.0,192.0,7.5,395.2,-0.282697
8,BRIAN,85.0,25.0,19.0,21.0,45.0,45.0,32.3,38.900000,Fail,F,5,25.0,90.0,9.0,420.2,-0.882619
9,OBAMA,23.0,50.0,44.0,36.0,45.0,23.6,36.0,36.800000,Fail,F,5,50.0,47.2,10.0,470.2,-1.094102
10,PUTIN,14.0,12.0,33.6,63.0,23.0,50.0,56.0,35.942857,Fail,F,5,12.0,100.0,11.0,482.2,-1.180421
11,STEWIE,45.0,14.0,62.0,12.0,63.0,5.0,45.0,35.142857,Fail,F,6,14.0,10.0,12.0,496.2,-1.260986

In [89]:
gh.to_csv('report.csv', index=False)

In [90]:
gh.to_excel('report.xlsx', index=False)